name: CI

on:
  push:
    branches: [ "kolosov" ]
  pull_request:
    branches: [ "kolosov" ]
  schedule:
    - cron: '30 12 * * 3' # Каждую среду в 12:30
    - cron: '0 22 * * 5'   # Каждую пятницу в 22:00

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Укажите нужную версию Java

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
